networks:
  yii:
    name: yii

services:
  nginx:
    container_name: nginx
    image: nginx:1.27.0
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - yii
    depends_on:
      - php

  php:
    container_name: php
    build: ./images/php
    volumes:
      - ./www:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - yii
    depends_on:
      - adminer

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - yii

  postgres:
    container_name: postgres
    image: postgres:16.3
    ports:
      - 5432:5432
    volumes:
      - ./www:/var/www
      - ./postgresql-data:/var/lib/postgresql
      - ./my.cnf:/etc/postgresql/conf.d/my.cnf
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_USER=postgres_user
      - POSTGRES_DB=postgres_db
    networks:
      - yii